import { Language } from './types';

export const CROPS = ['Rice', 'Wheat', 'Maize', 'Cotton', 'Sugarcane', 'Soybean'];
export const SOIL_TYPES = ['Alluvial', 'Black', 'Red', 'Laterite', 'Clay'];
export const SEASONS = ['Kharif', 'Rabi', 'Zaid'];
export const DISTRICTS = ['Pune', 'Nashik', 'Nagpur', 'Aurangabad', 'Solapur', 'Satara', 'Thane'];

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    appTitle: "Agri-Yield Assistant",
    dashboard: "Dashboard",
    predict: "Predict Yield",
    assistant: "Ask Assistant",
    weather: "Weather",
    history: "Farm History",
    risk: "Risk Analysis",
    welcome: "Welcome, Farmer",
    actions: "Quick Actions",
    recentAlerts: "Recent Alerts",
    yieldResult: "Estimated Yield",
    confidence: "Accuracy",
    savings: "Potential Savings",
    recommendation: "Recommendation",
    submit: "Calculate",
    listening: "Listening...",
    speak: "Tap to Speak",
    loading: "Analyzing...",
  },
  [Language.HINDI]: {
    appTitle: "कृषि उपज सहायक",
    dashboard: "डैशबोर्ड",
    predict: "उपज अनुमान",
    assistant: "सहायक से पूछें",
    weather: "मौसम",
    history: "खेत का इतिहास",
    risk: "जोखिम विश्लेषण",
    welcome: "स्वागत है, किसान भाई",
    actions: "त्वरित कार्य",
    recentAlerts: "हालिया चेतावनी",
    yieldResult: "अनुमानित उपज",
    confidence: "सटीकता",
    savings: "संभावित बचत",
    recommendation: "सुझाव",
    submit: "गणना करें",
    listening: "सुन रहा हूँ...",
    speak: "बोलने के लिए दबाएं",
    loading: "विश्लेषण कर रहा है...",
  },
  [Language.MARATHI]: {
    appTitle: "कृषी उत्पन्न सहाय्यक",
    dashboard: "डॅशबोर्ड",
    predict: "उत्पन्न अंदाज",
    assistant: "सहायक",
    weather: "हवामान",
    history: "शेतीचा इतिहास",
    risk: "जोखीम विश्लेषण",
    welcome: "स्वागत आहे, शेतकरी दादा",
    actions: "जलद क्रिया",
    recentAlerts: "अलीकडील सूचना",
    yieldResult: "अंदाजित उत्पन्न",
    confidence: "अचूकता",
    savings: "संभाव्य बचत",
    recommendation: "शिफारस",
    submit: "गणना करा",
    listening: "ऐकत आहे...",
    speak: "बोलण्यासाठी दाबा",
    loading: "विश्लेषण करत आहे...",
  },
  [Language.TELUGU]: {
    appTitle: "వ్యవసాయ దిగుబడి సహాయకుడు",
    dashboard: "డ్యాష్‌బోర్డ్",
    predict: "దిగుబడి అంచనా",
    assistant: "సహాయకుడిని అడగండి",
    weather: "వాతావరణం",
    history: "పంట చరిత్ర",
    risk: "ప్రమాద విశ్లేషణ",
    welcome: "స్వాగతం, రైతు",
    actions: "త్వరిత చర్యలు",
    recentAlerts: "ఇటీవలి హెచ్చరికలు",
    yieldResult: "అంచనా వేసిన దిగుబడి",
    confidence: "ఖచ్చితత్వం",
    savings: "ఆదా",
    recommendation: "సిఫార్సు",
    submit: "లెక్కించు",
    listening: "వింటున్నాను...",
    speak: "మాట్లాడటానికి నొక్కండి",
    loading: "విశ్లేషిస్తోంది...",
  },
  [Language.TAMIL]: {
    appTitle: "விவசாய விளைச்சல் உதவியாளர்",
    dashboard: "முகப்பு",
    predict: "விளைச்சல் கணிப்பு",
    assistant: "உதவியாளர்",
    weather: "வானிலை",
    history: "பண்ணை வரலாறு",
    risk: "ஆபத்து பகுப்பாய்வு",
    welcome: "வணக்கம், விவசாயி",
    actions: "விரைவான செயல்கள்",
    recentAlerts: "சமீபத்திய எச்சரிக்கைகள்",
    yieldResult: "மதிப்பிடப்பட்ட விளைச்சல்",
    confidence: "துல்லியம்",
    savings: "சேமிப்பு",
    recommendation: "பரிந்துரை",
    submit: "கணக்கிடு",
    listening: "கேட்கிறது...",
    speak: "பேச தட்டவும்",
    loading: "பகுப்பாய்வு...",
  },
  [Language.GUJARATI]: {
    appTitle: "કૃષિ ઉપજ સહાયક",
    dashboard: "ડેશબોર્ડ",
    predict: "ઉપજની આગાહી",
    assistant: "સહાયકને પૂછો",
    weather: "હવામાન",
    history: "ખેતરનો ઇતિહાસ",
    risk: "જોખમ વિશ્લેષણ",
    welcome: "સ્વાગત છે, ખેડૂત મિત્ર",
    actions: "ઝડપી ક્રિયાઓ",
    recentAlerts: "તાજેતરની ચેતવણીઓ",
    yieldResult: "અંદાજિત ઉપજ",
    confidence: "ચોકસાઈ",
    savings: "સંભવિત બચત",
    recommendation: "ભલામણ",
    submit: "ગણતરી કરો",
    listening: "સાંભળી રહ્યું છે...",
    speak: "બોલવા માટે ટેપ કરો",
    loading: "વિશ્લેષણ કરી રહ્યું છે...",
  },
  [Language.BANGLA]: {
    appTitle: "কৃষি ফলন সহায়ক",
    dashboard: "ড্যাশবোর্ড",
    predict: "ফলন পূর্বাভাস",
    assistant: "সহায়কারী",
    weather: "আবহাওয়া",
    history: "খামারের ইতিহাস",
    risk: "ঝুঁকি বিশ্লেষণ",
    welcome: "স্বাগতম, কৃষক বন্ধু",
    actions: "দ্রুত পদক্ষেপ",
    recentAlerts: "সাম্প্রতিক সতর্কতা",
    yieldResult: "আনুমানিক ফলন",
    confidence: "নির্ভুলতা",
    savings: "সম্ভাব্য সঞ্চয়",
    recommendation: "সুপারিশ",
    submit: "গণনা করুন",
    listening: "শুনছে...",
    speak: "কথা বলতে ট্যাপ করুন",
    loading: "বিশ্লেষণ করা হচ্ছে...",
  },
  [Language.URDU]: {
    appTitle: "زرعی پیداوار معاون",
    dashboard: "ڈیش بورڈ",
    predict: "پیداوار کی پیشین گوئی",
    assistant: "معاون سے پوچھیں",
    weather: "موسم",
    history: "فارم کی تاریخ",
    risk: "خطرات کا تجزیہ",
    welcome: "خوش آمدید، کسان بھائی",
    actions: "فوری اقدامات",
    recentAlerts: "حالیہ انتباہات",
    yieldResult: "متوقع پیداوار",
    confidence: "درستگی",
    savings: "ممکنہ بچت",
    recommendation: "تجویز",
    submit: "حساب لگائیں",
    listening: "سن رہا ہے...",
    speak: "بولنے کے لیے ٹیپ کریں",
    loading: "تجزیہ کر رہا ہے...",
  }
};